### PR TITLE
Fixed Request docs

### PR DESCRIPTION
**Pull request by petehalverson**
$app->request is a protected property, documentation code samples should reflect that.

### CODE REVIEW

**Comment by codeguy** [comment]
Request is a publicly-accessible object via the new DI container. Be sure you are running the latest code.

**Comment by petehalverson** [comment]
Ah. Using composer, "slim/slim": "2.*" pulls v2.2.0

**Comment by walker** [comment]
Why does 2.\* in composer still pull 2.2.x?

This is a good thing in the end, though, because 2.3.x isn't backwards compatible with 2.2.x. Ah well.

**Comment by petehalverson** [comment]
In my case it was because I didn't have mcrypt support in PHP. Once I had enabled that, composer pulled the latest version.

**Comment by walker** [comment]
Ah, yup, it fails backwards..and because 2.2 still satisfies 2._....it fails past 3._ on that.

**Comment by petehalverson** [comment]
Perhaps requirements should be more clear about mcrypt. The way it's worded, I didn't expect it to cause composer to resort to the earlier version.

https://github.com/codeguy/Slim-Documentation/blob/929f680de08cd916c489e70e98c26257e346d90b/01-getting-started/2-system-requirements/page.md

**Comment by cxj** [comment]
It would be nice to get these updated docs into the http://docs.slimframework.com/ website.  I just wasted too many minutes trying to debug my code when the problem was the documentation.  The corrections to the documentation I needed are here in this pull request.

**Pull request closed without merging**
